TARGET_CLASSES:
- 0
- 1
- 0
CONF: 0.5
IOU: 0.0
DELAY: 0.30000000000000004
VORSCHUSS: 0
NACHSCHUSS: 0
BEISCHUSS: 10
THRESHOLD: 1050.0
VERT_MOVEMENT: 35
CALIBRATED_VERT_MOVEMENT: 40.0
RUN_VERT_CALIBRATION: false
RECORD_RAW: false
DRAW_BBOXES: true
ROTATE: 4
FLIP_H: false
FLIP_V: false
RAW_RECORDING_FPS: 2.0
GUI_RECORDING_FPS: 2.0
FPS: 30
RAW_RECORDING_DIR: C:\Users\Technikum-Admin\Desktop\Gerald\SenSoRTC-NIR\SenSoRTC-NIR-MAIN\NIR\Recordings_NIR
GUI_RECORDING_DIR: Recordings_GUI
NIR_CLASS_COLORS:
- - 255
  - 255
  - 255
- - 255
  - 64
  - 64
- - 249
  - 254
  - 31
